import { dump } from 'js-yaml';

export interface AgentStackConfig {
  agentToken: string;
  agentImage: string;
  agentUpdaterImage: string;
  capabilities: {
    docker: boolean;
    zfs: boolean;
  };
  hlmZfsUid?: number;
  hlmZfsGid?: number;
  dockerGid?: number;
}

/** Generate a Docker Compose YAML string for the agent stack based on host capabilities. */
export function generateAgentStackCompose(config: AgentStackConfig): string {
  const { docker } = config.capabilities;
  const services: Record<string, unknown> = {};

  if (docker) {
    services['socket-proxy'] = buildSocketProxy();
  }

  services['agent'] = buildAgent(config);
  services['agent-updater'] = buildAgentUpdater();

  const doc: Record<string, unknown> = { services };

  if (docker) {
    doc['networks'] = {
      'agent-internal': {
        driver: 'bridge',
        internal: true,
      },
    };
  }

  const header = [
    '# homelab-manager agent stack',
    '# Generated by homelab-manager UI',
    '',
  ].join('\n');

  return header + dump(doc, { lineWidth: -1, quotingType: '"' });
}

/** Generate a .env file content string for the agent stack. */
export function generateAgentStackEnv(config: AgentStackConfig): string {
  const { docker, zfs } = config.capabilities;

  if (zfs) {
    if (config.hlmZfsUid === undefined || config.hlmZfsGid === undefined) {
      throw new Error('hlmZfsUid and hlmZfsGid are required when zfs capability is enabled');
    }
    if (docker && config.dockerGid === undefined) {
      throw new Error('dockerGid is required when both docker and zfs capabilities are enabled');
    }
  }

  const lines: string[] = [
    `AGENT_IMAGE=${config.agentImage}`,
    `AGENT_UPDATER_IMAGE=${config.agentUpdaterImage}`,
    `HLM_AGENT_PORT=9090`,
  ];

  if (zfs) {
    lines.push(`HLM_ZFS_UID=${config.hlmZfsUid}`);
    lines.push(`HLM_ZFS_GID=${config.hlmZfsGid}`);
  }

  if (docker && zfs) {
    lines.push(`DOCKER_GID=${config.dockerGid}`);
  }

  return lines.join('\n') + '\n';
}

function buildSocketProxy(): Record<string, unknown> {
  return {
    image: 'lscr.io/linuxserver/socket-proxy:latest',
    container_name: 'hlm-socket-proxy',
    restart: 'unless-stopped',
    volumes: ['/var/run/docker.sock:/var/run/docker.sock:ro'],
    environment: {
      CONTAINERS: 1,
      EVENTS: 1,
      INFO: 1,
      IMAGES: 1,
      NETWORKS: 1,
      VOLUMES: 1,
      VERSION: 1,
      ALLOW_START: 1,
      ALLOW_STOP: 1,
      ALLOW_RESTARTS: 1,
      POST: 1,
      EXEC: 1,
      CONTAINERS_CREATE: 1,
      CONTAINERS_DELETE: 1,
    },
    networks: ['agent-internal'],
  };
}

function buildAgent(config: AgentStackConfig): Record<string, unknown> {
  const { docker, zfs } = config.capabilities;

  const environment: Record<string, string> = {
    AGENT_TOKEN_FILE: '/run/secrets/agent_token',
  };

  if (docker) {
    environment['DOCKER_HOST'] = 'tcp://socket-proxy:2375';
  }

  const agent: Record<string, unknown> = {
    image: '${AGENT_IMAGE}',
    container_name: 'hlm-agent',
    restart: 'unless-stopped',
    ports: ['${HLM_AGENT_PORT:-9090}:9090'],
    environment,
    volumes: [] as string[],
  };

  const volumes: string[] = ['./agent-token:/run/secrets/agent_token:ro'];

  if (zfs) {
    volumes.push(
      '/usr/sbin/zpool:/usr/sbin/zpool:ro',
      '/usr/sbin/zfs:/usr/sbin/zfs:ro',
      '/dev/zfs:/dev/zfs'
    );
    agent['user'] = '${HLM_ZFS_UID}:${HLM_ZFS_GID}';
  }

  agent['volumes'] = volumes;

  if (docker && zfs) {
    agent['group_add'] = ['${DOCKER_GID}'];
  }

  if (docker) {
    agent['networks'] = ['agent-internal'];
    agent['depends_on'] = ['socket-proxy'];
  }

  agent['labels'] = ['hlm.managed=true', 'hlm.role=agent'];

  return agent;
}

function buildAgentUpdater(): Record<string, unknown> {
  return {
    image: '${AGENT_UPDATER_IMAGE}',
    container_name: 'hlm-agent-updater',
    restart: 'unless-stopped',
    volumes: ['/var/run/docker.sock:/var/run/docker.sock'],
    environment: {
      HLM_WATCH_CONTAINER: 'hlm-agent',
      HLM_WATCH_IMAGE: '${AGENT_IMAGE}',
      HLM_CHECK_INTERVAL: '${HLM_CHECK_INTERVAL:-6h}',
    },
    labels: ['hlm.managed=true', 'hlm.role=agent-updater'],
  };
}
