/**
 * Download ALL icons from Dashboard Icons repo.
 * Run with: bun scripts/download-icons.ts
 *
 * Icons are licensed under Apache 2.0 - see public/icons/LICENSE and public/icons/NOTICE
 *
 * @see https://github.com/walkxcode/dashboard-icons
 */
import { mkdir, writeFile, readdir } from 'fs/promises';
import { existsSync } from 'fs';

const ICONS_DIR = './public/icons';
const GITHUB_API =
  'https://api.github.com/repos/walkxcode/dashboard-icons/contents/svg';
const RAW_BASE =
  'https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg';

interface GitHubFile {
  name: string;
  type: 'file' | 'dir';
  download_url: string;
}

async function getIconList(): Promise<string[]> {
  console.log('Fetching icon list from GitHub API...');

  const response = await fetch(GITHUB_API, {
    headers: {
      Accept: 'application/vnd.github.v3+json',
      'User-Agent': 'homelab-manager',
    },
  });

  if (!response.ok) {
    throw new Error(
      `GitHub API error: ${response.status} ${response.statusText}`
    );
  }

  const files: GitHubFile[] = await response.json();
  return files
    .filter((f) => f.type === 'file' && f.name.endsWith('.svg'))
    .map((f) => f.name.replace('.svg', ''));
}

async function downloadIcon(slug: string): Promise<void> {
  const url = `${RAW_BASE}/${slug}.svg`;
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Failed to fetch ${slug}: ${response.status}`);
  }

  const svg = await response.text();
  await writeFile(`${ICONS_DIR}/${slug}.svg`, svg);
}

async function downloadIcons() {
  // Create icons directory
  if (!existsSync(ICONS_DIR)) {
    await mkdir(ICONS_DIR, { recursive: true });
  }

  // Get list of all icons from GitHub
  const icons = await getIconList();
  console.log(`Found ${icons.length} icons in Dashboard Icons repo`);

  // Download in batches to avoid overwhelming the network
  const BATCH_SIZE = 50;
  let downloaded = 0;
  let failed = 0;

  for (let i = 0; i < icons.length; i += BATCH_SIZE) {
    const batch = icons.slice(i, i + BATCH_SIZE);

    const results = await Promise.allSettled(batch.map((slug) => downloadIcon(slug)));

    downloaded += results.filter((r) => r.status === 'fulfilled').length;
    failed += results.filter((r) => r.status === 'rejected').length;

    console.log(
      `Progress: ${downloaded}/${icons.length} downloaded, ${failed} failed`
    );
  }

  console.log(`\nDone! Downloaded ${downloaded} icons to ${ICONS_DIR}`);
  if (failed > 0) {
    console.log(`Warning: ${failed} icons failed to download`);
  }

  // Generate icon manifest for the frontend
  await generateIconManifest();
}

async function generateIconManifest() {
  const files = await readdir(ICONS_DIR);
  const icons = files
    .filter((f) => f.endsWith('.svg'))
    .map((f) => f.replace('.svg', ''))
    .sort();

  const manifest = `// Auto-generated by scripts/download-icons.ts
// Do not edit manually - run \`bun icons:download\` to regenerate

export const AVAILABLE_ICONS = ${JSON.stringify(icons, null, 2)} as const;

export type IconSlug = (typeof AVAILABLE_ICONS)[number];
`;

  await writeFile('./src/lib/utils/available-icons.ts', manifest);
  console.log(`Generated icon manifest with ${icons.length} icons`);
}

downloadIcons().catch(console.error);
