/**
 * Download ALL icons from Dashboard Icons repo using sparse git clone.
 * Run with: bun scripts/download-icons.ts
 *
 * Icons are licensed under Apache 2.0 - see public/icons/LICENSE and public/icons/NOTICE
 *
 * @see https://github.com/homarr-labs/dashboard-icons
 */
import { mkdir, writeFile, readdir, cp, rm } from 'fs/promises';
import { existsSync } from 'fs';
import { execSync } from 'child_process';

const ICONS_DIR = './public/icons';
const REPO_URL = 'https://github.com/homarr-labs/dashboard-icons.git';
const TEMP_DIR = './tmp-dashboard-icons';

async function cloneIcons(): Promise<void> {
  // Clean up any previous temp directory
  if (existsSync(TEMP_DIR)) {
    await rm(TEMP_DIR, { recursive: true });
  }

  console.log('Cloning Dashboard Icons repo (sparse, svg/ only)...');

  // Shallow clone with no blobs, then sparse-checkout just the svg folder
  execSync(
    `git clone --depth 1 --filter=blob:none --sparse ${REPO_URL} ${TEMP_DIR}`,
    { stdio: 'inherit' }
  );
  execSync('git sparse-checkout set svg', {
    cwd: TEMP_DIR,
    stdio: 'inherit',
  });

  console.log('Clone complete.');
}

async function downloadIcons() {
  // Clone the repo
  await cloneIcons();

  // Create icons directory (preserve LICENSE and NOTICE)
  if (!existsSync(ICONS_DIR)) {
    await mkdir(ICONS_DIR, { recursive: true });
  }

  // Copy SVGs from cloned repo to public/icons/
  const svgDir = `${TEMP_DIR}/svg`;
  const files = await readdir(svgDir);
  const svgFiles = files.filter((f) => f.endsWith('.svg'));

  console.log(`Found ${svgFiles.length} icons, copying to ${ICONS_DIR}...`);

  for (const file of svgFiles) {
    await cp(`${svgDir}/${file}`, `${ICONS_DIR}/${file}`);
  }

  // Clean up temp directory
  await rm(TEMP_DIR, { recursive: true });
  console.log(`Copied ${svgFiles.length} icons to ${ICONS_DIR}`);

  // Generate icon manifest for the frontend
  await generateIconManifest();
}

async function generateIconManifest() {
  const files = await readdir(ICONS_DIR);
  const icons = files
    .filter((f) => f.endsWith('.svg'))
    .map((f) => f.replace('.svg', ''))
    .sort();

  const manifest = `// Auto-generated by scripts/download-icons.ts
// Do not edit manually - run \`bun icons:download\` to regenerate

export const AVAILABLE_ICONS = ${JSON.stringify(icons, null, 2)} as const;

export type IconSlug = (typeof AVAILABLE_ICONS)[number];
`;

  await writeFile('./src/lib/utils/available-icons.ts', manifest);
  console.log(`Generated icon manifest with ${icons.length} icons`);
}

downloadIcons().catch(console.error);
