/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZfsRouteImport } from './routes/zfs'
import { Route as StacksRouteImport } from './routes/stacks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProxmoxRouteImport } from './routes/proxmox'
import { Route as DockerRouteImport } from './routes/docker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksIndexRouteImport } from './routes/stacks/index'
import { Route as StacksStackNameRouteImport } from './routes/stacks/$stackName'
import { Route as DockerContainerIdRouteImport } from './routes/docker.$containerId'
import { Route as ApiZfsStatsRouteImport } from './routes/api/zfs-stats'
import { Route as ApiStackStatusRouteImport } from './routes/api/stack-status'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as ApiProxmoxStatsRouteImport } from './routes/api/proxmox-stats'
import { Route as ApiDockerStatsRouteImport } from './routes/api/docker-stats'
import { Route as StacksHostHostNameRouteImport } from './routes/stacks/host.$hostName'
import { Route as ApiGitSplatRouteImport } from './routes/api/git.$'
import { Route as ApiDockerLogsContainerIdRouteImport } from './routes/api/docker-logs.$containerId'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeniedRouteImport } from './routes/denied'

const ZfsRoute = ZfsRouteImport.update({
  id: '/zfs',
  path: '/zfs',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksRoute = StacksRouteImport.update({
  id: '/stacks',
  path: '/stacks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxmoxRoute = ProxmoxRouteImport.update({
  id: '/proxmox',
  path: '/proxmox',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerRoute = DockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksIndexRoute = StacksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StacksRoute,
} as any)
const StacksStackNameRoute = StacksStackNameRouteImport.update({
  id: '/$stackName',
  path: '/$stackName',
  getParentRoute: () => StacksRoute,
} as any)
const DockerContainerIdRoute = DockerContainerIdRouteImport.update({
  id: '/$containerId',
  path: '/$containerId',
  getParentRoute: () => DockerRoute,
} as any)
const ApiZfsStatsRoute = ApiZfsStatsRouteImport.update({
  id: '/api/zfs-stats',
  path: '/api/zfs-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStackStatusRoute = ApiStackStatusRouteImport.update({
  id: '/api/stack-status',
  path: '/api/stack-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxmoxStatsRoute = ApiProxmoxStatsRouteImport.update({
  id: '/api/proxmox-stats',
  path: '/api/proxmox-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDockerStatsRoute = ApiDockerStatsRouteImport.update({
  id: '/api/docker-stats',
  path: '/api/docker-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksHostHostNameRoute = StacksHostHostNameRouteImport.update({
  id: '/host/$hostName',
  path: '/host/$hostName',
  getParentRoute: () => StacksRoute,
} as any)
const ApiGitSplatRoute = ApiGitSplatRouteImport.update({
  id: '/api/git/$',
  path: '/api/git/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDockerLogsContainerIdRoute =
  ApiDockerLogsContainerIdRouteImport.update({
    id: '/api/docker-logs/$containerId',
    path: '/api/docker-logs/$containerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeniedRoute = DeniedRouteImport.update({
  id: '/denied',
  path: '/denied',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docker': typeof DockerRouteWithChildren
  '/proxmox': typeof ProxmoxRoute
  '/settings': typeof SettingsRoute
  '/stacks': typeof StacksRouteWithChildren
  '/zfs': typeof ZfsRoute
  '/api/docker-stats': typeof ApiDockerStatsRoute
  '/api/proxmox-stats': typeof ApiProxmoxStatsRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/stack-status': typeof ApiStackStatusRoute
  '/api/zfs-stats': typeof ApiZfsStatsRoute
  '/docker/$containerId': typeof DockerContainerIdRoute
  '/stacks/$stackName': typeof StacksStackNameRoute
  '/stacks/': typeof StacksIndexRoute
  '/api/docker-logs/$containerId': typeof ApiDockerLogsContainerIdRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/stacks/host/$hostName': typeof StacksHostHostNameRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/login': typeof LoginRoute
  '/denied': typeof DeniedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docker': typeof DockerRouteWithChildren
  '/proxmox': typeof ProxmoxRoute
  '/settings': typeof SettingsRoute
  '/zfs': typeof ZfsRoute
  '/api/docker-stats': typeof ApiDockerStatsRoute
  '/api/proxmox-stats': typeof ApiProxmoxStatsRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/stack-status': typeof ApiStackStatusRoute
  '/api/zfs-stats': typeof ApiZfsStatsRoute
  '/docker/$containerId': typeof DockerContainerIdRoute
  '/stacks/$stackName': typeof StacksStackNameRoute
  '/stacks': typeof StacksIndexRoute
  '/api/docker-logs/$containerId': typeof ApiDockerLogsContainerIdRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/stacks/host/$hostName': typeof StacksHostHostNameRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/login': typeof LoginRoute
  '/denied': typeof DeniedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docker': typeof DockerRouteWithChildren
  '/proxmox': typeof ProxmoxRoute
  '/settings': typeof SettingsRoute
  '/stacks': typeof StacksRouteWithChildren
  '/zfs': typeof ZfsRoute
  '/api/docker-stats': typeof ApiDockerStatsRoute
  '/api/proxmox-stats': typeof ApiProxmoxStatsRoute
  '/api/settings': typeof ApiSettingsRoute
  '/api/stack-status': typeof ApiStackStatusRoute
  '/api/zfs-stats': typeof ApiZfsStatsRoute
  '/docker/$containerId': typeof DockerContainerIdRoute
  '/stacks/$stackName': typeof StacksStackNameRoute
  '/stacks/': typeof StacksIndexRoute
  '/api/docker-logs/$containerId': typeof ApiDockerLogsContainerIdRoute
  '/api/git/$': typeof ApiGitSplatRoute
  '/stacks/host/$hostName': typeof StacksHostHostNameRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/login': typeof LoginRoute
  '/denied': typeof DeniedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docker'
    | '/proxmox'
    | '/settings'
    | '/stacks'
    | '/zfs'
    | '/api/docker-stats'
    | '/api/proxmox-stats'
    | '/api/settings'
    | '/api/stack-status'
    | '/api/zfs-stats'
    | '/docker/$containerId'
    | '/stacks/$stackName'
    | '/stacks/'
    | '/api/docker-logs/$containerId'
    | '/api/git/$'
    | '/stacks/host/$hostName'
    | '/api/auth/login'
    | '/api/auth/callback'
    | '/api/auth/logout'
    | '/login'
    | '/denied'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docker'
    | '/proxmox'
    | '/settings'
    | '/zfs'
    | '/api/docker-stats'
    | '/api/proxmox-stats'
    | '/api/settings'
    | '/api/stack-status'
    | '/api/zfs-stats'
    | '/docker/$containerId'
    | '/stacks/$stackName'
    | '/stacks'
    | '/api/docker-logs/$containerId'
    | '/api/git/$'
    | '/stacks/host/$hostName'
    | '/api/auth/login'
    | '/api/auth/callback'
    | '/api/auth/logout'
    | '/login'
    | '/denied'
  id:
    | '__root__'
    | '/'
    | '/docker'
    | '/proxmox'
    | '/settings'
    | '/stacks'
    | '/zfs'
    | '/api/docker-stats'
    | '/api/proxmox-stats'
    | '/api/settings'
    | '/api/stack-status'
    | '/api/zfs-stats'
    | '/docker/$containerId'
    | '/stacks/$stackName'
    | '/stacks/'
    | '/api/docker-logs/$containerId'
    | '/api/git/$'
    | '/stacks/host/$hostName'
    | '/api/auth/login'
    | '/api/auth/callback'
    | '/api/auth/logout'
    | '/login'
    | '/denied'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DockerRoute: typeof DockerRouteWithChildren
  ProxmoxRoute: typeof ProxmoxRoute
  SettingsRoute: typeof SettingsRoute
  StacksRoute: typeof StacksRouteWithChildren
  ZfsRoute: typeof ZfsRoute
  ApiDockerStatsRoute: typeof ApiDockerStatsRoute
  ApiProxmoxStatsRoute: typeof ApiProxmoxStatsRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiStackStatusRoute: typeof ApiStackStatusRoute
  ApiZfsStatsRoute: typeof ApiZfsStatsRoute
  ApiDockerLogsContainerIdRoute: typeof ApiDockerLogsContainerIdRoute
  ApiGitSplatRoute: typeof ApiGitSplatRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  LoginRoute: typeof LoginRoute
  DeniedRoute: typeof DeniedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zfs': {
      id: '/zfs'
      path: '/zfs'
      fullPath: '/zfs'
      preLoaderRoute: typeof ZfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks': {
      id: '/stacks'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof StacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxmox': {
      id: '/proxmox'
      path: '/proxmox'
      fullPath: '/proxmox'
      preLoaderRoute: typeof ProxmoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker': {
      id: '/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof DockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/': {
      id: '/stacks/'
      path: '/'
      fullPath: '/stacks/'
      preLoaderRoute: typeof StacksIndexRouteImport
      parentRoute: typeof StacksRoute
    }
    '/stacks/$stackName': {
      id: '/stacks/$stackName'
      path: '/$stackName'
      fullPath: '/stacks/$stackName'
      preLoaderRoute: typeof StacksStackNameRouteImport
      parentRoute: typeof StacksRoute
    }
    '/docker/$containerId': {
      id: '/docker/$containerId'
      path: '/$containerId'
      fullPath: '/docker/$containerId'
      preLoaderRoute: typeof DockerContainerIdRouteImport
      parentRoute: typeof DockerRoute
    }
    '/api/zfs-stats': {
      id: '/api/zfs-stats'
      path: '/api/zfs-stats'
      fullPath: '/api/zfs-stats'
      preLoaderRoute: typeof ApiZfsStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stack-status': {
      id: '/api/stack-status'
      path: '/api/stack-status'
      fullPath: '/api/stack-status'
      preLoaderRoute: typeof ApiStackStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxmox-stats': {
      id: '/api/proxmox-stats'
      path: '/api/proxmox-stats'
      fullPath: '/api/proxmox-stats'
      preLoaderRoute: typeof ApiProxmoxStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docker-stats': {
      id: '/api/docker-stats'
      path: '/api/docker-stats'
      fullPath: '/api/docker-stats'
      preLoaderRoute: typeof ApiDockerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/host/$hostName': {
      id: '/stacks/host/$hostName'
      path: '/host/$hostName'
      fullPath: '/stacks/host/$hostName'
      preLoaderRoute: typeof StacksHostHostNameRouteImport
      parentRoute: typeof StacksRoute
    }
    '/api/git/$': {
      id: '/api/git/$'
      path: '/api/git/$'
      fullPath: '/api/git/$'
      preLoaderRoute: typeof ApiGitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docker-logs/$containerId': {
      id: '/api/docker-logs/$containerId'
      path: '/api/docker-logs/$containerId'
      fullPath: '/api/docker-logs/$containerId'
      preLoaderRoute: typeof ApiDockerLogsContainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denied': {
      id: '/denied'
      path: '/denied'
      fullPath: '/denied'
      preLoaderRoute: typeof DeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DockerRouteChildren {
  DockerContainerIdRoute: typeof DockerContainerIdRoute
}

const DockerRouteChildren: DockerRouteChildren = {
  DockerContainerIdRoute: DockerContainerIdRoute,
}

const DockerRouteWithChildren =
  DockerRoute._addFileChildren(DockerRouteChildren)

interface StacksRouteChildren {
  StacksStackNameRoute: typeof StacksStackNameRoute
  StacksIndexRoute: typeof StacksIndexRoute
  StacksHostHostNameRoute: typeof StacksHostHostNameRoute
}

const StacksRouteChildren: StacksRouteChildren = {
  StacksStackNameRoute: StacksStackNameRoute,
  StacksIndexRoute: StacksIndexRoute,
  StacksHostHostNameRoute: StacksHostHostNameRoute,
}

const StacksRouteWithChildren =
  StacksRoute._addFileChildren(StacksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DockerRoute: DockerRouteWithChildren,
  ProxmoxRoute: ProxmoxRoute,
  SettingsRoute: SettingsRoute,
  StacksRoute: StacksRouteWithChildren,
  ZfsRoute: ZfsRoute,
  ApiDockerStatsRoute: ApiDockerStatsRoute,
  ApiProxmoxStatsRoute: ApiProxmoxStatsRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiStackStatusRoute: ApiStackStatusRoute,
  ApiZfsStatsRoute: ApiZfsStatsRoute,
  ApiDockerLogsContainerIdRoute: ApiDockerLogsContainerIdRoute,
  ApiGitSplatRoute: ApiGitSplatRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  LoginRoute: LoginRoute,
  DeniedRoute: DeniedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
