import { useState, useMemo } from 'react'
import {
  Typography,
  Button,
  Alert,
  Stepper,
  Step,
  StepLabel,
} from '@mui/material'
import { getAgentImage, getAgentUpdaterImage } from '@/lib/hosts/host-utils'
import { generateAgentStackCompose, generateAgentStackEnv } from '@/lib/templates/agent-stack-compose'
import CapabilitiesStep from '@/components/settings/wizard-steps/CapabilitiesStep'
import ZfsSetupStep from '@/components/settings/wizard-steps/ZfsSetupStep'
import ComposeFileStep from '@/components/settings/wizard-steps/ComposeFileStep'
import ConfigurationStep from '@/components/settings/wizard-steps/ConfigurationStep'
import VerifyConnectionStep from '@/components/settings/wizard-steps/VerifyConnectionStep'

const WIZARD_STEPS = ['Capabilities', 'ZFS Setup', 'Compose File', 'Configuration', 'Verify Connection'] as const

// Placeholder shown in the compose preview before the real pubkey is generated by the server.
const PUBKEY_PLACEHOLDER = '<AGENT_TRUSTED_PUBKEY will appear here after Verify Connection>'

interface AddHostWizardProps {
  isAdding: boolean
  addError: string | null
  onSubmit: (name: string, agentUrl: string, capabilities: { docker: boolean; zfs: boolean }) => void
  verifyResult: { publicJwk: unknown } | null
}

function parseGatedId(enabled: boolean, raw: string): number | undefined {
  if (!enabled || raw === '') return undefined
  return Number(raw)
}

export default function AddHostWizard({ isAdding, addError, onSubmit, verifyResult }: AddHostWizardProps) {
  const [activeStep, setActiveStep] = useState(0)
  const [docker, setDocker] = useState(true)
  const [zfs, setZfs] = useState(false)
  const [hlmZfsUid, setHlmZfsUid] = useState('')
  const [hlmZfsGid, setHlmZfsGid] = useState('')
  const [dockerGid, setDockerGid] = useState('')
  const [name, setName] = useState('')
  const [agentUrl, setAgentUrl] = useState('')

  const visibleSteps = useMemo(() => {
    if (zfs) return [...WIZARD_STEPS]
    return [WIZARD_STEPS[0], WIZARD_STEPS[2], WIZARD_STEPS[3], WIZARD_STEPS[4]]
  }, [zfs])

  const currentStepName = visibleSteps[activeStep]

  const agentStackConfig = useMemo(() => ({
    agentTrustedPubkey: PUBKEY_PLACEHOLDER,
    agentImage: getAgentImage(),
    agentUpdaterImage: getAgentUpdaterImage(),
    capabilities: { docker, zfs },
    hlmZfsUid: parseGatedId(zfs, hlmZfsUid),
    hlmZfsGid: parseGatedId(zfs, hlmZfsGid),
    dockerGid: parseGatedId(docker && zfs, dockerGid),
  }), [docker, zfs, hlmZfsUid, hlmZfsGid, dockerGid])

  const composeYaml = useMemo(() => {
    try {
      return generateAgentStackCompose(agentStackConfig)
    } catch {
      return '# Error generating compose file. Check ZFS UID/GID values.'
    }
  }, [agentStackConfig])

  const envFile = useMemo(() => {
    try {
      return generateAgentStackEnv(agentStackConfig)
    } catch {
      return '# Error generating .env file. Check ZFS UID/GID values.'
    }
  }, [agentStackConfig])

  function handleNext() {
    setActiveStep((prev) => Math.min(prev + 1, visibleSteps.length - 1))
  }

  function handleBack() {
    setActiveStep((prev) => Math.max(prev - 1, 0))
  }

  function handleVerify() {
    if (!name.trim() || !agentUrl.trim() || isAdding) return
    onSubmit(name.trim(), agentUrl.trim(), { docker, zfs })
  }

  function handleReset() {
    setActiveStep(0)
    setDocker(true)
    setZfs(false)
    setHlmZfsUid('')
    setHlmZfsGid('')
    setDockerGid('')
    setName('')
    setAgentUrl('')
  }

  const canProceedFromCapabilities = docker || zfs
  const isNonNegativeInt = (v: string) => /^\d+$/.test(v.trim())
  const canProceedFromZfs = isNonNegativeInt(hlmZfsUid) && isNonNegativeInt(hlmZfsGid)
    && (!docker || isNonNegativeInt(dockerGid))
  const canVerify = name.trim().length > 0 && agentUrl.trim().length > 0

  const publicJwkJson = verifyResult ? JSON.stringify(verifyResult.publicJwk) : null

  return (
    <div className="flex flex-col gap-4 pt-4 border-t border-(--mui-palette-divider)">
      <Typography variant="subtitle2">Add Host</Typography>

      <Stepper activeStep={activeStep} alternativeLabel>
        {visibleSteps.map((label) => (
          <Step key={label}>
            <StepLabel>{label}</StepLabel>
          </Step>
        ))}
      </Stepper>

      <div className="min-h-[200px]">
        {currentStepName === 'Capabilities' && (
          <CapabilitiesStep
            docker={docker}
            zfs={zfs}
            onDockerChange={setDocker}
            onZfsChange={setZfs}
          />
        )}

        {currentStepName === 'ZFS Setup' && (
          <ZfsSetupStep
            docker={docker}
            hlmZfsUid={hlmZfsUid}
            hlmZfsGid={hlmZfsGid}
            dockerGid={dockerGid}
            onHlmZfsUidChange={setHlmZfsUid}
            onHlmZfsGidChange={setHlmZfsGid}
            onDockerGidChange={setDockerGid}
          />
        )}

        {currentStepName === 'Compose File' && (
          <ComposeFileStep composeYaml={composeYaml} />
        )}

        {currentStepName === 'Configuration' && (
          <ConfigurationStep envFile={envFile} />
        )}

        {currentStepName === 'Verify Connection' && (
          <VerifyConnectionStep
            name={name}
            agentUrl={agentUrl}
            isAdding={isAdding}
            canVerify={canVerify}
            publicJwkJson={publicJwkJson}
            onNameChange={setName}
            onAgentUrlChange={setAgentUrl}
            onVerify={handleVerify}
          />
        )}
      </div>

      {addError && (
        <Alert severity="error" className="mt-1">
          {addError}
        </Alert>
      )}

      <div className="flex justify-between">
        <div>
          {activeStep > 0 && (
            <Button size="small" onClick={handleBack} disabled={isAdding}>
              Back
            </Button>
          )}
        </div>
        <div className="flex gap-2">
          <Button size="small" onClick={handleReset} disabled={isAdding}>
            Reset
          </Button>
          {currentStepName !== 'Verify Connection' && (
            <Button
              size="small"
              variant="contained"
              onClick={handleNext}
              disabled={
                (currentStepName === 'Capabilities' && !canProceedFromCapabilities)
                || (currentStepName === 'ZFS Setup' && !canProceedFromZfs)
              }
            >
              Next
            </Button>
          )}
        </div>
      </div>
    </div>
  )
}
